name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency:
  group: kamal-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: false

      - name: Install Kamal
        run: gem install kamal -v 2.11.0

      - name: Kamal deploy
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          HOST_IP: ${{ secrets.HOST_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CERTIFICATE_PEM: ${{ secrets.CERTIFICATE_PEM }}
          PRIVATE_KEY_PEM: ${{ secrets.PRIVATE_KEY_PEM }}
        run: kamal deploy
